name: Auto-Merge Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Merge
        uses: pullreminders/merge-action@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
