name: Bandit Code Scan

on:
  pull_request:
    branches:
      - master

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install PyGithub

      - name: Run Bandit scan
        run: |
          bandit -r . 

      - name: Comment on pull request if critical vulnerabilities are found
        uses: actions/github-script@v3
        if: steps.check_bandit_report.outputs.critical_vulnerabilities == '1'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github = context.github;
            const issueId = context.issue.number;
            const repo = context.repo;
            github.issues.createComment({
              issue_number: issueId,
              owner: repo.owner,
              repo: repo.repo,
              body: 'Block'
            });

      - name: Auto-merge pull request if no critical vulnerabilities are found
        if: steps.check_bandit_report.outputs.critical_vulnerabilities == '0'
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          method: "squash"
          commit-message: "Auto-merged pull request comment: Successful"
