name: Code Scan

on:
  pull_request:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit scan
        run: |
          bandit -r . -f json -o bandit-report.json

      - name: Check Bandit report
        id: check_bandit_report
        run: |
          python -c "import json; results = json.loads(open('bandit-report.json').read()); exit_code = 1 if any(issue['issue_severity'] in ('CRITICAL', 'HIGH') for issue in results['results']) else 0; print('::set-output name=exit_code::{}'.format(exit_code))"

      - name: Block PR with comment
        if: steps.check_bandit_report.outputs.exit_code == '1'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github = context.github
            const issueId = context.issue.number
            const repo = context.repo
            github.issues.createComment({
              issue_number: issueId,
              owner: repo.owner,
              repo: repo.repo,
              body: 'Block'
            })
