name: Code Scan

on:
  pull_request:
    branches:
      - master

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install PyGithub

      - name: Run Bandit scan
        run: |
          bandit -r .

      - name: Check Bandit report
        id: check_bandit
        run: |
          python -c "import json; results = json.loads(open('.bandit').read()); print('::set-output name=critical_vulnerabilities::{}'.format(1 if any(issue['issue_severity'] in ('CRITICAL', 'HIGH') for issue in results['results']) else 0))"

      - name: Comment on pull request
        uses: actions/github-script@v3
        if: steps.check_bandit.outputs.critical_vulnerabilities == '1'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github = context.github
            const issueId = context.issue.number
            const repo = context.repo
            github.issues.createComment({
              issue_number: issueId,
              owner: repo.owner,
              repo: repo.repo,
              body: 'Block'
            })
      - name: Merge pull requests (automerge-action)
        uses: pascalgn/automerge-action@v0.16.2
        if: steps.check_bandit.outputs.critical_vulnerabilities == '0'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          method: "squash"
          commit-message: "Auto-merged pull request: Successful"
