name: dependencycheck

on:
  workflow_run:
    workflows: ["Bandit Code Scan"]
    types:
      - completed

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety  # or other dependency scanner

      - name: Run dependency scan
        run: |
          safety check --full-report

      - name: Parse and print scan results
        run: |
          python -c "import subprocess; output = subprocess.check_output(['safety', 'check', '--full-report']); print(output.decode())"

      - name: Upload scan results
        uses: actions/upload-artifact@v2
        with:
          name: dependency-scan-results
          path: report.txt

