name: Generate SBOM

on:
  pull_request:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety  # or other dependency scanner

      - name: Run dependency scan
        run: |
          safety check --full-report

      - name: Parse and print scan results
        run: |
          python -c "import subprocess; output = subprocess.check_output(['safety', 'check', '--full-report']); print(output.decode())"

