name: Generate SBOM

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install CycloneDX Python package
        run: pip install cyclonedx-bom

      - name: Find cyclonedx-bom path
        id: find-cyclonedx-bom
        run: echo "::set-output name=path::$(which cyclonedx-bom)"

      - name: Generate SBOM
        run: ${{ steps.find-cyclonedx-bom.outputs.path }} . --output bom.xml

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: bom.xml
